# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3Nm6M5j_anFZnw4HDpCkjYlrdGQ0iM1
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

X, y_true = make_blobs(n_samples=300, centers=4, cluster_std=0.7, random_state=42)
# n_samples=300: creates 300 data points total.
# centers=4: generates 4 distinct blob clusters.
# cluster_std=0.7: controls how spread out (noisy) each blob is — lower means tighter clusters.
# random_state=42:  this just means "if I run this again, give me the exact same random dots" — like reusing the same dice roll so results don't change every time.
X_scaled = StandardScaler().fit_transform(X)
# Imagine one measurement is in inches and another is in miles. If you compared them directly, the "miles" number would seem way more important just because it's a bigger number — even if it's not actually more important.
#This step adjusts all numbers so they're on the same fair scale, like converting everything to the same units before comparing.

model = KMeans(n_clusters=4, init='k-means++', n_init=10, random_state=42)
# n_clusters=4 → "I want exactly 4 groups"
# init='k-means++' → a smarter way to place the starting guesses, so it doesn't get unlucky and produce bad groups
# n_init=10 → "try this whole process 10 times with different starting guesses, and keep the best result" — like taking 10 attempts and picking the cleanest one
labels = model.fit_predict(X_scaled)

plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=labels, cmap='viridis', s=30)
plt.scatter(model.cluster_centers_[:, 0], model.cluster_centers_[:, 1], c='red', marker='X', s=200)
plt.show()

inertias = []
K_range = range(1, 11)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)

plt.plot(K_range, inertias, marker='o')
plt.show()

